// <auto-generated />
using System;
using DotNet8.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNet8.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250920111904_FixCascadePaths_And_AddEmailToUser")]
    partial class FixCascadePaths_And_AddEmailToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNet8.WebApi.Entities.Baum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Breitengrad")
                        .HasColumnType("float");

                    b.Property<double>("Laengengrad")
                        .HasColumnType("float");

                    b.Property<int?>("LetzteKontrolleID")
                        .HasColumnType("int");

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LetzteKontrolleID");

                    b.ToTable("Baeume");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.Kontrolle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("NeuesKontrollIntervall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verkehrssicher")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BaumId");

                    b.ToTable("Kontrollen");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.Baum", b =>
                {
                    b.HasOne("DotNet8.WebApi.Entities.Kontrolle", "LetzteKontrolle")
                        .WithMany()
                        .HasForeignKey("LetzteKontrolleID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LetzteKontrolle");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.Kontrolle", b =>
                {
                    b.HasOne("DotNet8.WebApi.Entities.Baum", "Baum")
                        .WithMany("Kontrollen")
                        .HasForeignKey("BaumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Baum");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.Baum", b =>
                {
                    b.Navigation("Kontrollen");
                });
#pragma warning restore 612, 618
        }
    }
}
