// <auto-generated />
using System;
using DotNet8.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNet8.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129165807_ReplaceTrunkInclinationWithTrunkDiameters")]
    partial class ReplaceTrunkInclinationWithTrunkDiameters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArboriculturalMeasureInspection", b =>
                {
                    b.Property<int>("ArboriculturalMeasuresId")
                        .HasColumnType("integer");

                    b.Property<int>("InspectionsId")
                        .HasColumnType("integer");

                    b.HasKey("ArboriculturalMeasuresId", "InspectionsId");

                    b.HasIndex("InspectionsId");

                    b.ToTable("ArboriculturalMeasureInspection");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.ArboriculturalMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MeasureName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ArboriculturalMeasures");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.CrownInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AbioticDisturbance")
                        .HasColumnType("boolean");

                    b.Property<string>("AbioticDisturbanceDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BioticDisturbance")
                        .HasColumnType("boolean");

                    b.Property<string>("BioticDisturbanceDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BranchBreak")
                        .HasColumnType("boolean");

                    b.Property<string>("BranchBreakDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BranchBreakWound")
                        .HasColumnType("boolean");

                    b.Property<string>("BranchBreakWoundDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Burl")
                        .HasColumnType("boolean");

                    b.Property<string>("BurlDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Canker")
                        .HasColumnType("boolean");

                    b.Property<string>("CankerDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Cavity")
                        .HasColumnType("boolean");

                    b.Property<string>("CavityDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ClearanceProfile2_50m")
                        .HasColumnType("boolean");

                    b.Property<string>("ClearanceProfile2_50mDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ClearanceProfile4_50m")
                        .HasColumnType("boolean");

                    b.Property<string>("ClearanceProfile4_50mDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CompetingBranch")
                        .HasColumnType("boolean");

                    b.Property<string>("CompetingBranchDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CompetingTree")
                        .HasColumnType("boolean");

                    b.Property<string>("CompetingTreeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CompressionDamage")
                        .HasColumnType("boolean");

                    b.Property<string>("CompressionDamageDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CompressionFork")
                        .HasColumnType("boolean");

                    b.Property<string>("CompressionForkDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CrownSecured")
                        .HasColumnType("boolean");

                    b.Property<string>("CrownSecuredDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Deadwood")
                        .HasColumnType("boolean");

                    b.Property<string>("DeadwoodDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Deformed")
                        .HasColumnType("boolean");

                    b.Property<string>("DeformedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DryBranches")
                        .HasColumnType("boolean");

                    b.Property<string>("DryBranchesDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Dying")
                        .HasColumnType("boolean");

                    b.Property<string>("DyingDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Exudation")
                        .HasColumnType("boolean");

                    b.Property<string>("ExudationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForeignObject")
                        .HasColumnType("boolean");

                    b.Property<string>("ForeignObjectDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForeignVegetation")
                        .HasColumnType("boolean");

                    b.Property<string>("ForeignVegetationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForkCrack")
                        .HasColumnType("boolean");

                    b.Property<string>("ForkCrackDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForkedCrown")
                        .HasColumnType("boolean");

                    b.Property<string>("ForkedCrownDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FungalFruitingBody")
                        .HasColumnType("boolean");

                    b.Property<string>("FungalFruitingBodyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GraftPoint")
                        .HasColumnType("boolean");

                    b.Property<string>("GraftPointDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HabitatStructure")
                        .HasColumnType("boolean");

                    b.Property<string>("HabitatStructureDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IncludedBark")
                        .HasColumnType("boolean");

                    b.Property<string>("IncludedBarkDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InspectionId")
                        .HasColumnType("integer");

                    b.Property<bool>("LightningDamage")
                        .HasColumnType("boolean");

                    b.Property<string>("LightningDamageDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LongitudinalCrack")
                        .HasColumnType("boolean");

                    b.Property<string>("LongitudinalCrackDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OneSidedCrown")
                        .HasColumnType("boolean");

                    b.Property<string>("OneSidedCrownDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OpenDecay")
                        .HasColumnType("boolean");

                    b.Property<string>("OpenDecayDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OverloadedBranchOrCrown")
                        .HasColumnType("boolean");

                    b.Property<string>("OverloadedBranchOrCrownDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PruningWound")
                        .HasColumnType("boolean");

                    b.Property<string>("PruningWoundDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ResinFlow")
                        .HasColumnType("boolean");

                    b.Property<string>("ResinFlowDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RubbingBranches")
                        .HasColumnType("boolean");

                    b.Property<string>("RubbingBranchesDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SecondaryCrowns")
                        .HasColumnType("boolean");

                    b.Property<string>("SecondaryCrownsDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SlimeFlux")
                        .HasColumnType("boolean");

                    b.Property<string>("SlimeFluxDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TensionFork")
                        .HasColumnType("boolean");

                    b.Property<string>("TensionForkDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TopDieback")
                        .HasColumnType("boolean");

                    b.Property<string>("TopDiebackDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Topped")
                        .HasColumnType("boolean");

                    b.Property<string>("ToppedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TorsionCrack")
                        .HasColumnType("boolean");

                    b.Property<string>("TorsionCrackDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TreeInGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("TreeInGroupDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TreeIsDead")
                        .HasColumnType("boolean");

                    b.Property<string>("TreeIsDeadDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UnfavorableCrownDevelopment")
                        .HasColumnType("boolean");

                    b.Property<string>("UnfavorableCrownDevelopmentDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UtilityLineConflict")
                        .HasColumnType("boolean");

                    b.Property<string>("UtilityLineConflictDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WidowmakerBranch")
                        .HasColumnType("boolean");

                    b.Property<string>("WidowmakerBranchDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WithoutLeaderShoot")
                        .HasColumnType("boolean");

                    b.Property<string>("WithoutLeaderShootDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WoodpeckerHole")
                        .HasColumnType("boolean");

                    b.Property<string>("WoodpeckerHoleDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Wound")
                        .HasColumnType("boolean");

                    b.Property<bool>("WoundCallusClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("WoundCallusClosedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WoundDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WoundWithCallusRidge")
                        .HasColumnType("boolean");

                    b.Property<string>("WoundWithCallusRidgeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId")
                        .IsUnique();

                    b.ToTable("CrownInspections");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.GreenArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GreenAreas");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TreeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DevelopmentalStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSafeForTraffic")
                        .HasColumnType("boolean");

                    b.Property<int>("NewInspectionIntervall")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TreeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Vitality")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.StemBaseInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdventitiousRootFormation")
                        .HasColumnType("boolean");

                    b.Property<string>("AdventitiousRootFormationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BoreDust")
                        .HasColumnType("boolean");

                    b.Property<string>("BoreDustDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Bottleneck")
                        .HasColumnType("boolean");

                    b.Property<string>("BottleneckDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BulgeOrSwelling")
                        .HasColumnType("boolean");

                    b.Property<string>("BulgeOrSwellingDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Canker")
                        .HasColumnType("boolean");

                    b.Property<string>("CankerDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Cavity")
                        .HasColumnType("boolean");

                    b.Property<string>("CavityDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CompressionDamage")
                        .HasColumnType("boolean");

                    b.Property<string>("CompressionDamageDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Excavation")
                        .HasColumnType("boolean");

                    b.Property<string>("ExcavationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Exudation")
                        .HasColumnType("boolean");

                    b.Property<string>("ExudationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForeignObject")
                        .HasColumnType("boolean");

                    b.Property<string>("ForeignObjectDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForeignVegetation")
                        .HasColumnType("boolean");

                    b.Property<string>("ForeignVegetationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FungalFruitingBody")
                        .HasColumnType("boolean");

                    b.Property<string>("FungalFruitingBodyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GirdlingRoot")
                        .HasColumnType("boolean");

                    b.Property<string>("GirdlingRootDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GraftPoint")
                        .HasColumnType("boolean");

                    b.Property<string>("GraftPointDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HabitatStructures")
                        .HasColumnType("boolean");

                    b.Property<string>("HabitatStructuresDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InspectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OpenDecay")
                        .HasColumnType("boolean");

                    b.Property<string>("OpenDecayDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Overfilled")
                        .HasColumnType("boolean");

                    b.Property<string>("OverfilledDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ResinFlow")
                        .HasColumnType("boolean");

                    b.Property<string>("ResinFlowDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RootDamage")
                        .HasColumnType("boolean");

                    b.Property<string>("RootDamageDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SlimeFlux")
                        .HasColumnType("boolean");

                    b.Property<string>("SlimeFluxDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StemBaseThickened")
                        .HasColumnType("boolean");

                    b.Property<string>("StemBaseThickenedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StructuresAtStemBase")
                        .HasColumnType("boolean");

                    b.Property<string>("StructuresAtStemBaseDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StructuresNearTree")
                        .HasColumnType("boolean");

                    b.Property<string>("StructuresNearTreeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TreeOnSlope")
                        .HasColumnType("boolean");

                    b.Property<string>("TreeOnSlopeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId")
                        .IsUnique();

                    b.ToTable("StemBaseInspections");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.Tree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CrownAttachmentHeightMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("CrownDiameterMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("GreenAreaId")
                        .HasColumnType("integer");

                    b.Property<int?>("LastInspectionId")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfTrunks")
                        .HasColumnType("integer");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TrunkDiameter1")
                        .HasColumnType("double precision");

                    b.Property<double>("TrunkDiameter2")
                        .HasColumnType("double precision");

                    b.Property<double>("TrunkDiameter3")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Number")
                        .IsUnique();

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.TrunkInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AbioticDisturbance")
                        .HasColumnType("boolean");

                    b.Property<string>("AbioticDisturbanceDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BioticDisturbance")
                        .HasColumnType("boolean");

                    b.Property<string>("BioticDisturbanceDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BranchBreakWound")
                        .HasColumnType("boolean");

                    b.Property<string>("BranchBreakWoundDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BulgeOrSwelling")
                        .HasColumnType("boolean");

                    b.Property<string>("BulgeOrSwellingDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Burl")
                        .HasColumnType("boolean");

                    b.Property<string>("BurlDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Canker")
                        .HasColumnType("boolean");

                    b.Property<string>("CankerDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Cavity")
                        .HasColumnType("boolean");

                    b.Property<string>("CavityDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CompressionDamage")
                        .HasColumnType("boolean");

                    b.Property<string>("CompressionDamageDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CompressionFork")
                        .HasColumnType("boolean");

                    b.Property<string>("CompressionForkDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Deadwood")
                        .HasColumnType("boolean");

                    b.Property<string>("DeadwoodDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Deformed")
                        .HasColumnType("boolean");

                    b.Property<string>("DeformedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Exudation")
                        .HasColumnType("boolean");

                    b.Property<string>("ExudationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForeignObject")
                        .HasColumnType("boolean");

                    b.Property<string>("ForeignObjectDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForeignVegetation")
                        .HasColumnType("boolean");

                    b.Property<string>("ForeignVegetationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForkCrack")
                        .HasColumnType("boolean");

                    b.Property<string>("ForkCrackDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForkedTrunk")
                        .HasColumnType("boolean");

                    b.Property<string>("ForkedTrunkDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FungalFruitingBody")
                        .HasColumnType("boolean");

                    b.Property<string>("FungalFruitingBodyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GraftPoint")
                        .HasColumnType("boolean");

                    b.Property<string>("GraftPointDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HabitatStructures")
                        .HasColumnType("boolean");

                    b.Property<string>("HabitatStructuresDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IncludedBark")
                        .HasColumnType("boolean");

                    b.Property<string>("IncludedBarkDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InspectionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Leaning")
                        .HasColumnType("boolean");

                    b.Property<string>("LeaningDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LeavesBrokenOff")
                        .HasColumnType("boolean");

                    b.Property<string>("LeavesBrokenOffDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LightningDamage")
                        .HasColumnType("boolean");

                    b.Property<string>("LightningDamageDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LongitudinalCrack")
                        .HasColumnType("boolean");

                    b.Property<string>("LongitudinalCrackDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MowingDamage")
                        .HasColumnType("boolean");

                    b.Property<string>("MowingDamageDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OpenDecay")
                        .HasColumnType("boolean");

                    b.Property<string>("OpenDecayDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PruningWound")
                        .HasColumnType("boolean");

                    b.Property<string>("PruningWoundDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ResinFlow")
                        .HasColumnType("boolean");

                    b.Property<string>("ResinFlowDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SecondaryRadialGrowthMissing")
                        .HasColumnType("boolean");

                    b.Property<string>("SecondaryRadialGrowthMissingDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SlimeFlux")
                        .HasColumnType("boolean");

                    b.Property<string>("SlimeFluxDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SpiralGrain")
                        .HasColumnType("boolean");

                    b.Property<string>("SpiralGrainDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SupplyShadow")
                        .HasColumnType("boolean");

                    b.Property<string>("SupplyShadowDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TensionFork")
                        .HasColumnType("boolean");

                    b.Property<string>("TensionForkDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Topped")
                        .HasColumnType("boolean");

                    b.Property<string>("ToppedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TorsionCrack")
                        .HasColumnType("boolean");

                    b.Property<string>("TorsionCrackDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TreeRemoved")
                        .HasColumnType("boolean");

                    b.Property<string>("TreeRemovedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WidowmakerBranch")
                        .HasColumnType("boolean");

                    b.Property<string>("WidowmakerBranchDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Wobbles")
                        .HasColumnType("boolean");

                    b.Property<string>("WobblesDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WoodpeckerHole")
                        .HasColumnType("boolean");

                    b.Property<string>("WoodpeckerHoleDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Wound")
                        .HasColumnType("boolean");

                    b.Property<bool>("WoundCallusClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("WoundCallusClosedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WoundCallusRidge")
                        .HasColumnType("boolean");

                    b.Property<string>("WoundCallusRidgeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WoundDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId")
                        .IsUnique();

                    b.ToTable("TrunkInspections");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArboriculturalMeasureInspection", b =>
                {
                    b.HasOne("DotNet8.WebApi.Entities.ArboriculturalMeasure", null)
                        .WithMany()
                        .HasForeignKey("ArboriculturalMeasuresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNet8.WebApi.Entities.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.CrownInspection", b =>
                {
                    b.HasOne("DotNet8.WebApi.Entities.Inspection", "Inspection")
                        .WithOne("CrownInspection")
                        .HasForeignKey("DotNet8.WebApi.Entities.CrownInspection", "InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.StemBaseInspection", b =>
                {
                    b.HasOne("DotNet8.WebApi.Entities.Inspection", "Inspection")
                        .WithOne("StemBaseInspection")
                        .HasForeignKey("DotNet8.WebApi.Entities.StemBaseInspection", "InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.TrunkInspection", b =>
                {
                    b.HasOne("DotNet8.WebApi.Entities.Inspection", "Inspection")
                        .WithOne("TrunkInspection")
                        .HasForeignKey("DotNet8.WebApi.Entities.TrunkInspection", "InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("DotNet8.WebApi.Entities.Inspection", b =>
                {
                    b.Navigation("CrownInspection")
                        .IsRequired();

                    b.Navigation("StemBaseInspection")
                        .IsRequired();

                    b.Navigation("TrunkInspection")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
